
This notebook contains the code used to grab batting statistics from the "Advanced" page  of Fangraphs.com MLB stats  
Uses Selenium

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd
import numpy
import os
import seaborn
pd.set_option("display.max_columns",999)

In [20]:
#Opening Chromedriver via Selenium
chromedriver = "/Users/brian_newborn/Downloads/chromedriver" # path to the chromedriver executable
os.environ["webdriver.chrome.driver"] = chromedriver
driver = webdriver.Chrome(chromedriver)

In [21]:
#2010-2017 Batting Stats, Advanced
# url="https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=100&type=1&season=2017&month=0&season1=2010&ind=1&team=0&rost=0&age=0&filter=&players=0"
url="https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=100&type=6&season=2017&month=0&season1=2010&ind=1&team=0&rost=0&age=0&filter=&players=0"
driver.get(url)

#Need to Save Column Names
col_names_list = []
#Dictionary to save players and data
master_players={}

In [22]:
def one_section_only():
    '''
    This function works through a full section of Fangraphs (Standard, in this example).
    It will click the next page button until the end of the section is reached.
    '''
    try:
        next_pg = driver.find_element_by_xpath('//a[@title="Next Page"]')
        next_pg.send_keys(u'\ue007')
        print("Next Page")
        keep_running=True
    except:
        print("End of Section")
        keep_running =False
    return keep_running

def col_headers():
    #Grab Headers
    identifier_header = "rgHeader"
    
    col_names = driver.find_elements_by_class_name(identifier_header)
    curr_page = driver.find_element_by_xpath\
    ('.//div[@class = "rgWrap rgNumPart"]//a[@class="rgCurrentPage"]').text
    for n in col_names[4:]:
        col_names_list.append(n.text)
        print(n.text)
    return col_names_list

def scrape_players():  
    #Grab Players - 2 Types of HTML rows
    identifier1,identifier2 = "rgRow","rgAltRow"

    players = driver.find_elements_by_class_name(identifier2)
    players2 = driver.find_elements_by_class_name(identifier1)
    players = players+players2
    
    for player in players:
        player = player.find_elements_by_tag_name("td")
#         player = player.find_elements_by_class_name("grid_line_regular") #td elements-need each element       
        name =  (player[2].text)+' '+(player[1].text) #name + year
#         print(f"Name: {name}")
        for td in player:
            if name in master_players: #if player already exists, append item to 
                master_players[name].append(td.text)

            else:
                master_players[name]=[td.text]

In [23]:
columns = col_headers()

Batting
Base Running
Fielding
Positional
Offense
Defense
League
Replacement
RAR
WAR
Dollars

In [24]:
keep_running = True #flag to keep loop going
#Call scraper once
scrape_players()
#Go into loop. End when one_section_only returns False
while keep_running == True:
        keep_running = one_section_only()
        scrape_players()

Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
Next Page
End of Section

In [25]:
#Create df from dictionary master_players
df = pd.DataFrame.from_dict(data=master_players,orient="index")
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
Mike Trout 2012,2,2012,Mike Trout,Angels,50.1,14.3,10.4,-0.2,64.4,10.2,2.2,18.9,95.6,10.0,$65.1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Jacoby Ellsbury 2011,4,2011,Jacoby Ellsbury,Red Sox,42.4,5.1,16.0,2.0,47.5,18.0,2.4,21.3,89.1,9.4,$71.6,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Mike Trout 2015,6,2015,Mike Trout,Angels,55.7,3.0,4.7,1.9,58.7,6.6,2.2,19.9,87.5,9.3,$74.3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Miguel Cabrera 2013,8,2013,Miguel Cabrera,Tigers,68.6,-6.0,-6.0,2.0,62.6,-4.0,2.4,18.6,79.6,8.6,$63.6,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
Matt Kemp 2011,10,2011,Matt Kemp,Dodgers,54.3,5.6,-4.8,2.2,59.9,-2.7,1.4,20.0,78.7,8.3,$63.2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [26]:
columns

['Batting',
 'Base Running',
 'Fielding',
 'Positional',
 'Offense',
 'Defense',
 'League',
 'Replacement',
 'RAR',
 'WAR',
 'Dollars']

In [27]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
Gerardo Parra 2016,3559,2016,Gerardo Parra,Rockies,-19.6,-3.7,-3.1,-3.9,-23.3,-7.0,0.7,11.5,-18.1,-1.9,($14.8),3559,2016,Gerardo Parra,Rockies,-19.6,-3.7,-3.1,-3.9,-23.3,-7.0,0.7,11.5,-18.1,-1.9,($14.8)
Raul Ibanez 2011,3561,2011,Raul Ibanez,Phillies,-6.6,-3.7,-19.2,-6.3,-10.3,-25.5,1.1,16.7,-17.9,-1.9,($14.4),3561,2011,Raul Ibanez,Phillies,-6.6,-3.7,-19.2,-6.3,-10.3,-25.5,1.1,16.7,-17.9,-1.9,($14.4)
Victor Martinez 2015,3563,2015,Victor Martinez,Tigers,-13.1,-7.3,-2.1,-12.0,-20.4,-14.1,1.6,14.2,-18.8,-2.0,($15.9),3563,2015,Victor Martinez,Tigers,-13.1,-7.3,-2.1,-12.0,-20.4,-14.1,1.6,14.2,-18.8,-2.0,($15.9)
Felix Pie 2011,3565,2011,Felix Pie,Orioles,-11.0,-0.2,-13.5,-2.2,-11.2,-15.7,0.6,5.1,-21.3,-2.3,($17.1),3565,2011,Felix Pie,Orioles,-11.0,-0.2,-13.5,-2.2,-11.2,-15.7,0.6,5.1,-21.3,-2.3,($17.1)
Adam Dunn 2011,3567,2011,Adam Dunn,White Sox,-22.9,-5.4,-4.2,-11.3,-28.3,-15.5,1.6,14.4,-27.8,-2.9,($22.3),3567,2011,Adam Dunn,White Sox,-22.9,-5.4,-4.2,-11.3,-28.3,-15.5,1.6,14.4,-27.8,-2.9,($22.3)

In [28]:
#Remove unnecessary columns
df = df.drop(labels=range(15,30,1),axis=1)

In [29]:
df = df.drop(labels=[0,1,2,3],axis=1)

In [30]:
# len(col_names_list) #18
col_names_list

['Batting',
 'Base Running',
 'Fielding',
 'Positional',
 'Offense',
 'Defense',
 'League',
 'Replacement',
 'RAR',
 'WAR',
 'Dollars']

In [31]:
df.head()

,4,5,6,7,8,9,10,11,12,13,14
Mike Trout 2012,50.1,14.3,10.4,-0.2,64.4,10.2,2.2,18.9,95.6,10.0,$65.1
Jacoby Ellsbury 2011,42.4,5.1,16.0,2.0,47.5,18.0,2.4,21.3,89.1,9.4,$71.6
Mike Trout 2015,55.7,3.0,4.7,1.9,58.7,6.6,2.2,19.9,87.5,9.3,$74.3
Miguel Cabrera 2013,68.6,-6.0,-6.0,2.0,62.6,-4.0,2.4,18.6,79.6,8.6,$63.6
Matt Kemp 2011,54.3,5.6,-4.8,2.2,59.9,-2.7,1.4,20.0,78.7,8.3,$63.2

In [32]:
#Name columns to match website
df.columns = col_names_list

In [33]:
df.loc["Mike Trout 2012"]

Batting          50.1
Base Running     14.3
Fielding         10.4
Positional       -0.2
Offense          64.4
Defense          10.2
League            2.2
Replacement      18.9
RAR              95.6
WAR              10.0
Dollars         $65.1
Name: Mike Trout 2012, dtype: object

In [34]:
import pickle
#Pickle df to save
with open('df_value.pkl', 'wb') as picklefile:
    pickle.dump(df, picklefile)